GC_FUNCTIONS = True
USE_SERIAL = True
# STAGE1_ONLY = True
# BKLIGHT_ON = True
# USE_NAND = True
# USE_UBI = True

BOARD := lepus

VARIANTS := lepus
JZ_VERSION = 4760

CFLAGS_all := -mips32 -DSDRAM_HY5PS1G1631CFP_S6=1 -DDDR_DW32=0
# CFLAGS_all := -mips32 -DSDRAM_H5PS1G63EFR_S6C=1 -DDDR_DW32=0
